let CountryVignette = [
  {
    id: 1,
    country: "Austria",
    card: "https://cdn.britannica.com/20/191120-050-B6C0B7E9/village-Hallstatt-Alps-Austria.jpg",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/800px-Flag_of_Austria.svg.png?20220412141234",
    priceForTwoMonth: "32,00",
    priceForOneMonth: "28,90",
    priceForYear: "96,40",
    priceFor7Day: "16,00",
    vehicleType: {
      typeCars: "Cars",
      typeMotor: "Motorcycle",
      typeTruck: "Trucks",
      typeCarsCamp: "Cars with camp house",
    },
    description:
      "In Austria, a vignette is required to use motorways and expressways. There are two types of vignettes. On the one hand, the well-known adhesive vignette, also affectionately called “Pickerl” or “Plakete”, as well as the modern form, the digital vignette. The advantages are apparent. In addition, there are tolls for pass roads, such as the Brenner motorway and Tauern motorway, as well as bridges and tunnels. A GO-box is required for vehicles with a GVW of over 3.5 tonnes.",
  },
  {
    id: 2,
    country: "Slovenia",
    card: "https://cdn.britannica.com/79/124479-050-DD359499/Ljubljana-Slovenia.jpg",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/2560px-Flag_of_Slovenia.svg.png",
    priceForTwoMonth: "29,00",
    priceForOneMonth: "25,90",
    priceForYear: "90,40",
    priceFor7Day: "13,00",
    vehicleType: {
      typeCars: "Cars",
      typeMotor: "Motorcycle",
      typeTruck: "Trucks",
      typeCarsCamp: "Cars with camp house",
    },
    description:
      "A digital vignette, the so-called electronic vignette E-Vinjeta, is required to use Slovenian motorways and expressways. In addition, toll fees are due when driving through the Karawanken Tunnel. However, this only applies to vehicles under 3.5 tonnes. For vehicles over 3.5 tonnes, a DarsGo transmitter is required.",
  },
  {
    id: 3,
    country: "Switzerland",
    card: "https://s30876.pcdn.co/wp-content/uploads/Switzerland-e1634207571492-1170x630.jpg.optimal.jpg",
    flag: "https://uxwing.com/wp-content/themes/uxwing/download/flags-landmarks/switzerland-flag-icon.png",
    priceForTwoMonth: "31,00",
    priceForOneMonth: "28,70",
    priceForYear: "89,40",
    priceFor7Day: "15,90",
    vehicleType: {
      typeCars: "Cars",
      typeMotor: "Motorcycle",
      typeTruck: "Trucks",
      typeCarsCamp: "Cars with camp house",
    },
    description:
      "Just like in Austria, there are still two types of vignettes in Switzerland. The classic variant of the adhesive vignette and the digital vignette. The advantages of the digital vignette are obvious. The vignette is mandatory for the use of Swiss motorways. Every car and every trailer with a GVW of up to 3.5 tonnes requires an annual vignette. Different regulations apply to vehicles over 3.5 tonnes. They must pay a Swiss customs tax upon entry.",
  },
  {
    id: 4,
    country: "Romania",
    card: "https://www.spectator.co.uk/wp-content/uploads/2023/07/Neil-Clark-iStock.jpg?w=1000",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/2560px-Flag_of_Romania.svg.png",
    priceForTwoMonth: "28,50",
    priceForOneMonth: "22,70",
    priceForYear: "103,40",
    priceFor7Day: "36,90",
    vehicleType: {
      typeCars: "Cars",
      typeMotor: "Motorcycle",
      typeTruck: "Trucks",
      typeCarsCamp: "Cars with camp house",
    },
    description:
      "A digital vignette, the Rovinieta, is required to drive on national roads in Romania. The Rovinieta can be purchased online, but also at border crossings and gas stations. However, the advantage of buying online is obvious. The Romanian national road network is subject to tolls for motor vehicles, with the exception of motorcycles. Additional tolls apply for using the Danube crossing towards Bulgaria.",
  },
  {
    id: 5,
    country: "Hungary",
    card: "https://i.natgeofe.com/n/7e9d29f5-16ef-4224-abd1-39fce220a029/ST_whatsnew_budapest_C98P0J_ukHR.jpg",
    flag: "https://cdn.britannica.com/55/1455-004-5897143C/Flag-Hungary.jpg",
    priceForTwoMonth: "22,50",
    priceForOneMonth: "29,70",
    priceForYear: "67,40",
    priceFor7Day: "82,90",
    vehicleType: {
      typeCars: "Cars",
      typeMotor: "Motorcycle",
      typeTruck: "Trucks",
      typeCarsCamp: "Cars with camp house",
    },
    description:
      "In order to be able to drive on motorways and expressways in Hungary, cars, trailers and mobile homes require a digital vignette, the electronic vignette e-Matrica. All Hungarian motorways marked with an “M” require a vignette for all vehicles. The digital vignette in Hungary is available online but also at selected points of sale. Trucks over 3.5 tonnes permissible gross vehicle weight (GVW) and trailers must purchase route tickets via HU-Go.",
  },
  {
    id: 6,
    country: "Czech Republic",
    card: "https://cdn.britannica.com/69/99569-050-F226F189/Prague.jpg",
    flag: "https://cdn.britannica.com/86/7886-050-9D2D04BC/Flag-Czech-Republic.jpg",
    priceForTwoMonth: "25,50",
    priceForOneMonth: "49,70",
    priceForYear: "87,40",
    priceFor7Day: "32,90",
    vehicleType: {
      typeCars: "Cars",
      typeMotor: "Motorcycle",
      typeTruck: "Trucks",
      typeCarsCamp: "Cars with camp house",
    },
    description:
      "A digital vignette is required in the Czech Republic to use motorways and expressways with a car with a GVW of up to 3.5 tonnes. The digital vignette is available online and on site. However, it is advisable to buy the vignette online before traveling to avoid stress. For vehicles over 3.5 tonnes GVW, a route-dependent toll is due using a transmitter.",
  },
  {
    id: 7,
    country: "Slovakia",
    card: "https://cdn.britannica.com/16/90316-050-3D376CFA/Bratislava-Castle-Old-Town-Slvk.jpg",
    flag: "https://cdn.britannica.com/88/7888-050-2DD04243/Flag-Slovakia.jpg",
    priceForTwoMonth: "35,50",
    priceForOneMonth: "29,70",
    priceForYear: "107,40",
    priceFor7Day: "22,90",
    vehicleType: {
      typeCars: "Cars",
      typeMotor: "Motorcycle",
      typeTruck: "Trucks",
      typeCarsCamp: "Cars with camp house",
    },
    description:
      "All motorways and expressways in Slovakia are subject to tolls for motor vehicles up to 3.5 tonnes permissible gross vehicle weight (GVW), with the exception of motorcycles. A digital vignette is required for use. Motorhomes are charged regardless of the permissible gross vehicle weight (GVW) and always require a vignette. Motor vehicles with a gross vehicle weight of over 3.5 tonnes, with the exception of trailers and mobile homes, are charged a route-dependent toll using a transmitter (on-board unit) on motorways, expressways and some selected sections of so-called 1st and 2nd class roads. The e-vignette can be purchased locally at selected points of sale or online. The advantage of buying online is obvious.",
  },
  {
    id: 8,
    country: "Bulgaria",
    card: "https://media.cnn.com/api/v1/images/stellar/prod/200819101903-03-reconnect-bulgaria-highlights-veliko-tarnovo.jpg?q=w_4242,h_2387,x_0,y_0,c_fill",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/2000px-Flag_of_Bulgaria.svg.png",
    priceForTwoMonth: "26,80",
    priceForOneMonth: "34,90",
    priceForYear: "89,40",
    priceFor7Day: "28,90",
    vehicleType: {
      typeCars: "Cars",
      typeMotor: "Motorcycle",
      typeTruck: "Trucks",
      typeCarsCamp: "Cars with camp house",
    },
    description:
      "To use national roads in Bulgaria, a digital vignette is mandatory for all vehicles with a GVW of up to 3.5 tonnes, with the exception of motorcycles. For vehicles over 3.5 tonnes GVW, a route toll is due, which is paid using a passport or transmitter. In addition, there are additional fees for crossing the Danube towards Romania. The digital vignette for Bulgaria can be purchased online or at selected points of sale.",
  },
  {
    id: 9,
    country: "Serbia",
    card: "https://eige.europa.eu/sites/default/files/styles/original_optimized/public/images/shutterstock_695817316_0.jpg?itok=wh38DsMS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1200px-Flag_of_Serbia.svg.png",
    priceForTwoMonth: "28,80",
    priceForOneMonth: "39,90",
    priceForYear: "119,40",
    priceFor7Day: "18,90",
    vehicleType: {
      typeCars: "Cars",
      typeMotor: "Motorcycle",
      typeTruck: "Trucks",
      typeCarsCamp: "Cars with camp house",
    },
    description:
      "In Serbia, a vignette is not required, but a toll is necessary. This motorway toll is calculated based on the distance traveled. Serbia currently does not have a digital toll system. This means that the route toll is usually due at toll stations. However, Serbia plans to introduce a digital toll system with an digital e-vignette at the end of 2024.",
  },
];
export default CountryVignette;
